export const rocketQuotes = [
  "SPLURT!",
  "Time is an illusion. Lunchtime doubly so.",
  "Ford, you’re turning into a penguin. Stop it.",
  "Life! Don’t talk to me about life.",
  "In the beginning there was nothing, which exploded.",
  "Real stupidity beats artificial intelligence every time.",
  "Divide By Cucumber Error. Please Reinstall Universe And Reboot",
  "Oh lord, heal this bike.",
  "Don’t talk to me about the greater good, sunshine.",
  "Everybody’s dead, Dave.",
  "Smoke me a kipper, I’ll be back for breakfast.",
  "I’m fine, thank you, Susan.",
  "I toast, therefore I am.",
  "Shut up and take my money!",
  "Bite my shiny metal ass!",
  "Stop exploding, you cowards!",
  "I don’t want to live on this planet anymore.",
  "I’m surrounded by assholes!",
  "They’ve gone to plaid!",
  "I am your father’s brother’s nephew’s cousin’s former roommate.",
  "Ludicrous speed! Go!",
  "By Grabthar’s Hammer… what a savings.",
  "I see you managed to get your shirt off.",
  "Whoever wrote this episode should die!",
  "Miners. Not minors.",
  "Anybody want a peanut?",
  "I’m not a witch, I’m your wife!",
  "Have fun storming the castle!",
  "You’ve been mostly dead all day.",
  "‘Tis but a scratch.",
  "It’s just a flesh wound.",
  "I fart in your general direction!",
  "Help, help, I’m being repressed!",
  "This… is my boomstick!",
  "Gimme some sugar, baby.",
  "Good, bad… I’m the guy with the gun.",
  "Hail to the king, baby!",
  "Back off, man. I’m a scientist.",
  "We came, we saw, we kicked its ass!",
  "That’s a big Twinkie.",
  "Dogs and cats living together, mass hysteria!",
] as const;
